TransbankDevelopers/transbank-pos-sdk-nodejs

- examples/index.js
- src/pos.js
Add suport to multicode and change sale (0270)
> Add suport to multicode and change sale (0270)

- CHANGELOG.md
- package.json
You can see full diff here: https://github.com/TransbankDevelopers/transbank-pos-sdk-nodejs/compare/1.0.2...chore/prepare-release-1.1.0
> Prepare release 1.1.0

- src/pos.js
Las variables` waiting, isConnected y port` se resetean al desenchufar el pos, o apagar la máquina.
También cambié en la consola los carácteres que se imprimian como ▯, ahora se imprimen como {0x06} por ejemplo
> added on close function and pretty print in the console data

- src/responseCodes.js
> Add intermediate response 80

- CHANGELOG.md
- package-lock.json
- package.json
Full diff: https://github.com/TransbankDevelopers/transbank-pos-sdk-nodejs/compare/2.0.0...chore/prepare-release-2.1.0
> Prepare release 2.1.0

- src/pos.js
Add baudrate option to autoconnect
> Add baudrate option to autoconnect

- CHANGELOG.md
Full diff: https://github.com/TransbankDevelopers/transbank-pos-sdk-nodejs/compare/2.1.0...chore/prepare-release-2.1.1
> Prepare release 2.1.1

- .gitignore
- .travis.yml
- package.sh
> Improve deployment script

- CHANGELOG.md
Full diff: https://github.com/TransbankDevelopers/transbank-pos-sdk-nodejs/compare/2.1.1...chore/prepare-release-2.1.2
> Prepare release 2.1.2

- src/PosBase.js
- src/PosIntegrado.js
Autoservicio intermediate messages need this
> Move intermediate response to posbase

- CHANGELOG.md
- package.json
> Prepare release 3.0.0

- README.md
> docs: add new standards in readme

- package-lock.json
- package.json
- src/PosBase.js
This PR solves a reconnection issue that occurred when the POS was already connected to a serial port.
Test:
> fix: resolve reconnection problems

- src/PosBase.js
Simplify logs for debug
Before:
After:
Test
> feat: simplify logs

- examples/index.js
- src/PosAutoservicio.js
- src/PosIntegrado.js
> fix: code smells sonarcloud

- src/PosAutoservicio.js
- src/PosBase.js
- src/PosIntegrado.js
- src/responseCodes.js
Resolve Kiuwan report issues
Test
> fix: kiuwan report

- package-lock.json
- package.json
- src/PosBase.js
revert commits who updates serial port library
- ff5778d4651808f9ac0ed722572029cff8ccbf66
- 618a23b51ba7131ab0cfcafcd5632a1eca0954f9
Autoconnect:
LoadKeys:
Sale:
Refund:
SalesDetail:
closeDay:
> revert: update from serial port library

- src/PosBase.js
Add logs when send an ack.
Before:
Now:
> feat: add ack log

- CHANGELOG.md
- package.json
Prepare release from version 3.0.2
> chore: prepare release 3.0.2

- examples/index.js
- src/PosBase.js
This PR improve disconnect flow
> feat: improve disconnect

- examples/index.js
- index.js
- webpack.config.js
> fix: kiuwan alerts
